//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurvivorApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SurvivorEntities : DbContext
    {
        public SurvivorEntities()
            : base("name=SurvivorEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RESOURCE> RESOURCES { get; set; }
        public virtual DbSet<ROBOT> ROBOTS { get; set; }
        public virtual DbSet<SURVIVOR> SURVIVORS { get; set; }
    }
}
