//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurvivorApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROBOT
    {
        public int ID { get; set; }
        public string model { get; set; }
        public string serialNumber { get; set; }
        public Nullable<System.DateTime> manufacturedDate { get; set; }
        public string category { get; set; }
    }
}
