//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurvivorApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class SURVIVOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SURVIVOR()
        {
            this.RESOURCES = new HashSet<RESOURCE>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<byte> Age { get; set; }
        public string Gender { get; set; }
        public string IDNumber { get; set; }
        public Nullable<int> Reported { get; set; }
        public Nullable<bool> Infected { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESOURCE> RESOURCES { get; set; }
    }
}
